proxy-groups:
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - DIRECT
  - name: ğŸ“¹ YouTube
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - DIRECT 
  - name: ğŸ€ Google
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - DIRECT
  - name: ğŸ¤– ChatGPT
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - DIRECT
  - name: ğŸ’» GitHub
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - DIRECT
  - name: ğŸ¬ Twitter
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - DIRECT
  - name: ğŸªŸ Microsoft
    type: select
    proxies:
      - DIRECT
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
  - name: ğŸµ TikTok
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - DIRECT
  - name: ğŸ“² Telegram
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - DIRECT
  - name: ğŸ¥ Netflix
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - DIRECT
  - name: ğŸ“· Instagram
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - DIRECT
  - name: ğŸ’¶ PayPal
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - DIRECT
  - name: ğŸ Apple
    type: select
    proxies:
      - DIRECT
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
      - ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
      - DIRECT


  - name: ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹
    include-all: true
    filter: (?i)å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan
    type: select
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    include-all: true
    filter: (?i)æ¸¯|HK|hk|Hong Kong|HongKong|hongkong
    type: select
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    include-all: true
    filter: (?i)æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan
    type: select
  - name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
    include-all: true
    filter: (?i)ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States
    type: select
  - name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
    include-all: true
    filter: (?i)æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore
    type: select
  - name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
    include-all: true
    filter: (?i)KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“
    type: select
  - name: â™»ï¸ é¦™æ¸¯è‡ªåŠ¨
    include-all: true
    filter: (?i)æ¸¯|HK|hk|Hong Kong|HongKong|hongkong
    type: url-test
    interval: 300
    tolerance: 50
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    include-all: true
    interval: 300
    tolerance: 50
  - name: ğŸŒ å…¨éƒ¨èŠ‚ç‚¹
    include-all: true
    type: select

rule-providers:
  LocalAreaNetwork:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
    path: ./ruleset/LocalAreaNetwork.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  UnBan:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
    path: ./ruleset/UnBan.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BanAD:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    path: ./ruleset/BanAD.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BanProgramAD:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
    path: ./ruleset/BanProgramAD.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Google:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
    path: ./ruleset/Google.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  GoogleCN:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
    path: ./ruleset/GoogleCN.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  SteamCN:
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
    path: ./ruleset/SteamCN.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  GitHub:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GitHub.list
    path: ./ruleset/GitHub.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Microsoft:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
    path: ./ruleset/Microsoft.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Apple:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
    path: ./ruleset/Apple.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Telegram:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
    path: ./ruleset/Telegram.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChatGPT:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
    path: ./ruleset/OpenAi.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Twitter:
    url: https://gh.stfsub.us.kg/https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/Ruleset/Twitter.list
    path: ./ruleset/Twitter.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  TikTok:
    url: https://gh.stfsub.us.kg/https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/Ruleset/TikTok.list
    path: ./ruleset/TikTok.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Instagram:
    url: https://gh.stfsub.us.kg/https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/Ruleset/Instagram.list
    path: ./ruleset/Instagram.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  PayPal:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.list
    path: ./ruleset/PayPal.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Steam:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
    path: ./ruleset/Steam.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  YouTube:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
    path: ./ruleset/YouTube.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Netflix:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
    path: ./ruleset/Netflix.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  BilibiliHMT:
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
    path: ./ruleset/BilibiliHMT.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  Bilibili:
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
    path: ./ruleset/Bilibili.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChinaMedia:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
    path: ./ruleset/ChinaMedia.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ProxyMedia:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
    path: ./ruleset/ProxyMedia.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ProxyGFWlist:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
    path: ./ruleset/ProxyGFWlist.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  ChinaDomain:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
    path: ./ruleset/ChinaDomain.list
    behavior: domain
    interval: 86400
    format: text
    type: http
  ChinaCompanyIp:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
    path: ./ruleset/ChinaCompanyIp.list
    behavior: ipcidr
    interval: 86400
    format: text
    type: http
  Download:
    url: https://gh.stfsub.us.kg/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
    path: ./ruleset/Download.list
    behavior: classical
    interval: 86400
    format: text
    type: http

rules:
  - "RULE-SET,LocalAreaNetwork,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,UnBan,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,Google,ğŸ€ Google"
  - "RULE-SET,GoogleCN,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,SteamCN,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,GitHub,ğŸ’» GitHub"
  - "RULE-SET,Microsoft,ğŸªŸ Microsoft"
  - "RULE-SET,Apple,ğŸ Apple"
  - "RULE-SET,Telegram,ğŸ“² Telegram"
  - "RULE-SET,Twitter,ğŸ¬ Twitter"
  - "RULE-SET,ChatGPT,ğŸ¤– ChatGPT"
  - "RULE-SET,TikTok,ğŸµ TikTok"
  - "RULE-SET,Instagram,ğŸ“· Instagram"
  - "RULE-SET,PayPal,ğŸ’¶ PayPal"
  - "RULE-SET,Steam,â™»ï¸ é¦™æ¸¯è‡ªåŠ¨"
  - "RULE-SET,YouTube,ğŸ“¹ YouTube"
  - "RULE-SET,Netflix,ğŸ¥ Netflix"
  - "RULE-SET,ProxyMedia,ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
  - "RULE-SET,ProxyGFWlist,ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
  - "RULE-SET,BilibiliHMT,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,Bilibili,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,ChinaMedia,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,ChinaDomain,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,ChinaCompanyIp,ğŸ¯ å…¨çƒç›´è¿"
  - "RULE-SET,Download,ğŸ¯ å…¨çƒç›´è¿"
  - "GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿"
  - "MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼"
