u: &u { type: url-test, tolerance: 1, strategy: consistent-hashing, url: https://www.gstatic.com/generate_204, interval: 300, lazy: true, timeout: 5000, max-failed-times: 5, include-all: true }
domain_mrs: &domain_mrs { type: http, interval: 86400, behavior: domain, format: mrs, proxy: ğŸ¯å…¨çƒç›´è¿ }
ipcidr_mrs: &ipcidr_mrs { type: http, interval: 86400, behavior: ipcidr, format: mrs, proxy: ğŸ¯å…¨çƒç›´è¿ }

proxy-groups:
  - { name: ğŸš€å…¨çƒä»£ç†, type: select, proxies: [â™»ï¸è‡ªåŠ¨é€‰æ‹©, ğŸŸ¢æ‰‹åŠ¨é€‰æ‹©, âš¡ï¸å‡è¡¡è´Ÿè½½, ğŸ”¯æ•…éšœè½¬ç§», ğŸ¯å…¨å±€ç›´è¿] }
  - { name: ğŸŸ¢æ‰‹åŠ¨é€‰æ‹©, <<: *u, type: select }
  - { name: ğŸ¯å…¨å±€ç›´è¿, type: select, hidden: true, proxies: [DIRECT] }
  - { name: ğŸš«æ‹’ç»è¿æ¥, type: select, hidden: true, proxies: [REJECT] }
  - { name: ğŸš«é™é»˜æ‹’ç», type: select, hidden: true, proxies: [REJECT-DROP] }
  - { name: âšªç»•è¿‡è¿æ¥, type: select, hidden: true, proxies: [PASS] }
  - { name: ğŸ¯å…¨çƒç›´è¿, type: select, proxies: [ğŸ¯å…¨å±€ç›´è¿, ğŸš€å…¨çƒä»£ç†, ğŸŸ¢æ‰‹åŠ¨é€‰æ‹©, â™»ï¸è‡ªåŠ¨é€‰æ‹©] }
  - { name: â™»ï¸è‡ªåŠ¨é€‰æ‹©, <<: *u, tolerance: 1, type: url-test }
  - { name: âš¡ï¸å‡è¡¡è´Ÿè½½, <<: *u, strategy: round-robin, type: load-balance }
  - { name: ğŸ”¯æ•…éšœè½¬ç§», <<: *u, type: fallback }
  ############ å…¨å›½å®¶åˆ†ç»„è‡ªåŠ¨é€‰æ‹© ############
  - { name: GLOBAL, type: select, include-all: true, proxies: [ ğŸš€å…¨çƒä»£ç†, ğŸŸ¢æ‰‹åŠ¨é€‰æ‹©, ğŸ¯å…¨çƒç›´è¿, â™»ï¸è‡ªåŠ¨é€‰æ‹©, âš¡ï¸å‡è¡¡è´Ÿè½½, ğŸ”¯æ•…éšœè½¬ç§» ], icon: https://jsd.onmicrosoft.cn/gh/Kwisma/rules@main/icon/webp/100/GLOBAL.webp }

rules:
  - SUB-RULE,(OR,((NETWORK,UDP),(NETWORK,TCP))),SUB-RULES
  - MATCH,ğŸš€å…¨çƒä»£ç†
sub-rules:
  SUB-RULES:
    - OR,((AND,((RULE-SET,cn_domain),(RULE-SET,cn_ip))),(RULE-SET,cn_ip),(RULE-SET,private_domain),(RULE-SET,private_ip,no-resolve)),ğŸ¯å…¨çƒç›´è¿
rule-providers:
  cn_domain:
    <<: *domain_mrs
    url: "https://jsd.onmicrosoft.cn/gh/Kwisma/clash-rules@release/direct.mrs"
    path: ./ruleset/CN_Domain.mrs
  cn_ip:
    <<: *ipcidr_mrs
    url: "https://jsd.onmicrosoft.cn/gh/Kwisma/clash-rules@release/cncidr.mrs"
    path: ./ruleset/CN_IP.mrs
  private_domain:
    <<: *domain_mrs
    url: "https://jsd.onmicrosoft.cn/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs"
    path: ./ruleset/Private_Domain.mrs
  private_ip:
    <<: *ipcidr_mrs
    url: "https://jsd.onmicrosoft.cn/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/private.mrs"
    path: ./ruleset/Private_IP.mrs